### ISSUE TITLE
Food & Drink Vendor Bad faction 

### ISSUE THREAD

**Issue by Ho2x** [azerothcore/mod-guildhouse#36]
horde side the seller is aggressive

**Comment by pangolp** [comment]
Is this failure still ongoing? I have been testing the module in the alliance, now I will try to test it.
But maybe this was fixed some time ago.

**Comment by AldebaraanMKII** [comment]
Still happening. Horde character. Food vendor spawns a alliance dwarf.
